/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.projeto_3.view;

import br.com.projeto_3.ctr.ClienteCTR;
import br.com.projeto_3.dto.ClienteDTO;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
/**
 *
 * @author svitorz
 */
public class ClienteView extends javax.swing.JInternalFrame {

  /**
   * Creates new form ClienteView
   */
  public ClienteView() {
    initComponents();
    liberaCampos(false);
    liberaBotoes(true, false, false, false, true);
    modelo_jtl_consultar = (DefaultTableModel) tableConsulta.getModel();
  }

  private ClienteDTO dto = new ClienteDTO();
  private ClienteCTR ctr = new ClienteCTR();

  int gravar_alterar;

  ResultSet rs;

  // componente para manipular as linhas da tabela
  DefaultTableModel modelo_jtl_consultar;

  public void setPosicao() {
    Dimension d = this.getDesktopPane().getSize();
    this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nome_cli = new javax.swing.JTextField();
        logradouro_cli = new javax.swing.JTextField();
        bairro_cli = new javax.swing.JTextField();
        cidade_cli = new javax.swing.JTextField();
        rg_cli = new javax.swing.JTextField();
        btnSair = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        lblNome = new javax.swing.JLabel();
        lblBairro = new javax.swing.JLabel();
        lblLogradouro = new javax.swing.JLabel();
        numero_cli = new javax.swing.JTextField();
        lblLogradouro1 = new javax.swing.JLabel();
        estado_cli = new javax.swing.JComboBox<>();
        lblEstado = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        lblRg = new javax.swing.JLabel();
        cpf_cli = new javax.swing.JTextField();
        lblCpf = new javax.swing.JLabel();
        cep_cli = new javax.swing.JTextField();
        lblCep = new javax.swing.JLabel();
        lblTituloConsulta = new javax.swing.JLabel();
        lblConsulta = new javax.swing.JLabel();
        inpConsulta = new javax.swing.JTextField();
        btnConsulta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableConsulta = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel1.setText("Cliente");

        nome_cli.setNextFocusableComponent(logradouro_cli);

        logradouro_cli.setNextFocusableComponent(numero_cli);

        bairro_cli.setNextFocusableComponent(cidade_cli);

        cidade_cli.setNextFocusableComponent(estado_cli);
        cidade_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidade_cliActionPerformed(evt);
            }
        });

        rg_cli.setNextFocusableComponent(btnSalvar);

        btnSair.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/projeto_3/view/images/sair.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/projeto_3/view/images/excluir.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/projeto_3/view/images/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/projeto_3/view/images/salvar.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnNovo.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/projeto_3/view/images/novo.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        lblNome.setText("Nome");

        lblBairro.setText("Bairro");

        lblLogradouro.setText("Logradouro");

        numero_cli.setNextFocusableComponent(bairro_cli);

        lblLogradouro1.setText("Número");

        estado_cli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "ES", "GO", "DF", "MA", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        estado_cli.setNextFocusableComponent(cep_cli);

        lblEstado.setText("Estado");

        lblCidade.setText("Cidade");

        lblRg.setText("RG");

        cpf_cli.setNextFocusableComponent(rg_cli);

        lblCpf.setText("CPF");

        cep_cli.setNextFocusableComponent(cpf_cli);

        lblCep.setText("CEP");

        lblTituloConsulta.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        lblTituloConsulta.setText("Consulta");

        lblConsulta.setText("Nome:");

        btnConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/projeto_3/view/images/pesquisar.png"))); // NOI18N
        btnConsulta.setText("Consultar");
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });

        tableConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableConsultaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableConsulta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloConsulta)
                .addGap(110, 110, 110))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblLogradouro1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numero_cli))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblNome)
                                .addGap(24, 24, 24)
                                .addComponent(nome_cli, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCidade)
                                    .addComponent(lblCep)
                                    .addComponent(lblRg))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cidade_cli)
                                    .addComponent(cep_cli)
                                    .addComponent(rg_cli))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLogradouro)
                            .addComponent(lblBairro)
                            .addComponent(lblEstado)
                            .addComponent(lblCpf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(estado_cli, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logradouro_cli, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                            .addComponent(bairro_cli)
                            .addComponent(cpf_cli))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNovo)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(btnSair)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblConsulta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inpConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnConsulta))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloConsulta)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nome_cli, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNome)
                            .addComponent(lblConsulta)
                            .addComponent(lblLogradouro)
                            .addComponent(logradouro_cli, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                            .addComponent(inpConsulta))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLogradouro1)
                            .addComponent(numero_cli, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBairro)
                            .addComponent(bairro_cli, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCidade)
                            .addComponent(cidade_cli, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEstado)
                            .addComponent(estado_cli, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCep)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cep_cli, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblCpf)
                                .addComponent(cpf_cli, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(lblRg))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(rg_cli, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNovo)
                            .addComponent(btnCancelar)
                            .addComponent(btnExcluir)
                            .addComponent(btnSair)
                            .addComponent(btnSalvar))
                        .addGap(15, 15, 15))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableConsultaMouseClicked
        // TODO add your handling code here:
        preencheCampos(Integer.parseInt(
                String.valueOf(
                        tableConsulta.getValueAt(
                                tableConsulta.getSelectedRow(), 0))));
        liberaBotoes(false, true, true, true, true);
    }//GEN-LAST:event_tableConsultaMouseClicked

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        excluir();
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void cidade_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidade_cliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidade_cliActionPerformed

  private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSairActionPerformed
    // TODO add your handling code here:
     this.dispose();
  }// GEN-LAST:event_btnSairActionPerformed

  private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnNovoActionPerformed
    // TODO add your handling code here:
    liberaCampos(true);
    liberaBotoes(false, true, true, false, true);
    gravar_alterar = 1;
  }// GEN-LAST:event_btnNovoActionPerformed

  private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSalvarActionPerformed
    // TODO add your handling code here:
    if (gravar_alterar == 1) {
      criar();
    } else if(gravar_alterar == 2) {
        atualizar();
    } else {
        JOptionPane.showMessageDialog(null, "Erro no sistema.");
    }
    
    gravar_alterar = 0;

    limpaCampos();
    liberaCampos(false);
    liberaBotoes(true, false, false, false, true);
  }// GEN-LAST:event_btnSalvarActionPerformed

  private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCancelarActionPerformed
    // TODO add your handling code here:
    limpaCampos();
    liberaBotoes(true, false, false, false, true);
    liberaCampos(false);
    limpaTabela();
    gravar_alterar = 0;
  }// GEN-LAST:event_btnCancelarActionPerformed

  private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnConsultaActionPerformed
    // TODO add your handling code here:
    preencheTabela(inpConsulta.getText().toUpperCase());
  }// GEN-LAST:event_btnConsultaActionPerformed

  /**
   * aux methods
   */
  private void liberaCampos(boolean permission) {
    nome_cli.setEnabled(permission);
    logradouro_cli.setEnabled(permission);
    bairro_cli.setEnabled(permission);
    cep_cli.setEnabled(permission);
    cidade_cli.setEnabled(permission);
    cpf_cli.setEnabled(permission);
    estado_cli.setEnabled(permission);
    numero_cli.setEnabled(permission);
    rg_cli.setEnabled(permission);
  }

  private void limpaCampos() {
    nome_cli.setText("");
    logradouro_cli.setText("");
    bairro_cli.setText("");
    cep_cli.setText("");
    cidade_cli.setText("");
    cpf_cli.setText("");
    numero_cli.setText("");
    rg_cli.setText("");
  }

  private void liberaBotoes(boolean enableNovo, boolean enableSalvar, boolean enableCancelar, boolean enableExcluir,
      boolean enableSair) {
    btnNovo.setEnabled(enableNovo);
    btnSalvar.setEnabled(enableSalvar);
    btnCancelar.setEnabled(enableCancelar);
    btnExcluir.setEnabled(enableExcluir);
    btnSair.setEnabled(enableSair);
  }

  /**
   * database methodss
   */
  private void criar() {
    try {
        setDto();
        JOptionPane.showMessageDialog(null,
            ctr.inserirCliString(dto));
    } catch (Exception e) {
      System.out.println("Erro ao gravar na ClienteVIEW: " + e);
    }
  }
  
  private void atualizar(){
      try {
          setDto();
          JOptionPane.showMessageDialog(null, 
                  ctr.atualizarCliente(dto));
      } catch (Exception e) {
          JOptionPane.showMessageDialog(null, "Não atualizado." + e.getMessage());
      }
  }
  
  private void excluir(){
      if (JOptionPane.showConfirmDialog(null, "Deseja Realmente excluir o cliente?", "Aviso", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null,
                    ctr.excluirCliente(dto)
            );
       }
      limpaCampos();
      liberaCampos(false);
      liberaBotoes(true, false, false, false, true);
      limpaTabela();
  }
  
  private void limpaTabela(){
      modelo_jtl_consultar.setNumRows(0);
  }

  private void preencheTabela(String nome_cli) {
    try {
      limpaTabela();
      dto.setNome_cli(nome_cli);

      rs = ctr.consultarCliente(dto, 1);

      while (rs.next()) {
        modelo_jtl_consultar.addRow(new Object[] {
            rs.getInt("id_cli"),
            rs.getString("nome_cli"),
        });
      }
    } catch (Exception erTab) {
      System.out.println("Erro ao listar clientes: " + erTab);
      JOptionPane.showMessageDialog(null, "Ocorreu um erro ao exibir os valores" + erTab);
    } finally {
      ctr.CloseDB();
    }
  }

  private void preencheCampos(int id_cli) {
    try {
      dto.setId_cli(id_cli);

      rs = ctr.consultarCliente(dto, 2);

      if (rs.next()) {
        limpaCampos();

        nome_cli.setText(rs.getString("nome_cli"));
        bairro_cli.setText(rs.getString("bairro_cli"));
        cep_cli.setText(rs.getString("cep_cli"));
        cidade_cli.setText(rs.getString("cidade_cli"));
        cpf_cli.setText(rs.getString("cpf_cli"));
        estado_cli.setSelectedItem(rs.getString("estado_cli"));
        logradouro_cli.setText(rs.getString("logradouro_cli"));
        numero_cli.setText(rs.getString("numero_cli"));
        rg_cli.setText(rs.getString("rg_cli"));

        gravar_alterar = 2;
        liberaCampos(true);
      }
    } catch (Exception erTab) {
        JOptionPane.showMessageDialog(null, erTab);
    } finally {
      ctr.CloseDB();
    }
  }
  
  private void setDto() {
      dto.setNome_cli(nome_cli.getText());
      dto.setBairro_cli(bairro_cli.getText());
      dto.setCep_cli(cep_cli.getText());
      dto.setCidade_cli(cidade_cli.getText());
      dto.setCpf_cli(cpf_cli.getText());
      dto.setEstado_cli(String.valueOf(estado_cli.getSelectedItem()));
      dto.setLogradouro_cli(logradouro_cli.getText());
      dto.setNumero_cli(Integer.parseInt(numero_cli.getText()));
      dto.setRg_cli(rg_cli.getText());
  }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bairro_cli;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConsulta;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField cep_cli;
    private javax.swing.JTextField cidade_cli;
    private javax.swing.JTextField cpf_cli;
    private javax.swing.JComboBox<String> estado_cli;
    private javax.swing.JTextField inpConsulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblConsulta;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblLogradouro;
    private javax.swing.JLabel lblLogradouro1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblRg;
    private javax.swing.JLabel lblTituloConsulta;
    private javax.swing.JTextField logradouro_cli;
    private javax.swing.JTextField nome_cli;
    private javax.swing.JTextField numero_cli;
    private javax.swing.JTextField rg_cli;
    private javax.swing.JTable tableConsulta;
    // End of variables declaration//GEN-END:variables
}
