/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.projeto_avaliacao_1.view;

import br.com.projeto_avaliacao_1.ctr.VeiculoCTR;
import br.com.projeto_avaliacao_1.dto.VeiculoDTO;
import java.awt.Dimension;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;

/**
 *
 * @author svitorz
 */
public class VeiculoVIEW extends javax.swing.JInternalFrame {

  int gravar_alterar;
  ResultSet rs;
  DefaultTableModel modelo_jtl_consultar_veiculo;
  
  VeiculoDTO dto = new VeiculoDTO();
  VeiculoCTR ctr = new VeiculoCTR();

  /**
   * Creates new form VeiculoVIEW
   */
  public VeiculoVIEW() {
    initComponents();

    liberaCampos(false);
    liberaBotoes(true, false, false, false, true);
    modelo_jtl_consultar_veiculo = (DefaultTableModel) tableVeiculos.getModel();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblMarca = new javax.swing.JLabel();
        inpMarca = new javax.swing.JTextField();
        lblModelo = new javax.swing.JLabel();
        inpModelo = new javax.swing.JTextField();
        inpAno = new javax.swing.JTextField();
        lblAno = new javax.swing.JLabel();
        inpCor = new javax.swing.JTextField();
        lblCor = new javax.swing.JLabel();
        lblPlaca = new javax.swing.JLabel();
        inpPlaca = new javax.swing.JTextField();
        inpChassi = new javax.swing.JTextField();
        lblChassi = new javax.swing.JLabel();
        inpComb = new javax.swing.JTextField();
        lblCombustivel = new javax.swing.JLabel();
        inpQuil = new javax.swing.JTextField();
        lblQuil = new javax.swing.JLabel();
        inpPreco = new javax.swing.JTextField();
        lblPreco = new javax.swing.JLabel();
        lblProprietario = new javax.swing.JLabel();
        inpProprietario = new javax.swing.JTextField();
        inpDataCad = new javax.swing.JTextField();
        lblDataCad = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVeiculos = new javax.swing.JTable();
        btnConsultar = new javax.swing.JButton();
        inpConsultar = new javax.swing.JTextField();

        jLabel1.setText("Cadastro de Veículos");

        lblMarca.setText("Marca");

        inpMarca.setNextFocusableComponent(inpModelo);

        lblModelo.setText("Modelo");

        inpModelo.setNextFocusableComponent(inpAno);

        inpAno.setNextFocusableComponent(inpCor);

        lblAno.setText("Ano");

        inpCor.setNextFocusableComponent(inpPlaca);

        lblCor.setText("Cor");

        lblPlaca.setText("Placa");

        inpPlaca.setNextFocusableComponent(inpChassi);

        inpChassi.setNextFocusableComponent(inpComb);

        lblChassi.setText("Chassi");

        inpComb.setNextFocusableComponent(inpQuil);

        lblCombustivel.setText("Combustivel");

        inpQuil.setNextFocusableComponent(inpPreco);

        lblQuil.setText("Quilometragem");

        inpPreco.setNextFocusableComponent(inpProprietario);

        lblPreco.setText("Preço");

        lblProprietario.setText("Proprietário");

        inpProprietario.setNextFocusableComponent(lblDataCad);

        lblDataCad.setText("Data Cadastro");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblMarca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inpMarca))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblModelo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inpModelo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblAno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inpAno))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inpCor))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblPlaca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inpPlaca))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblChassi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inpChassi))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCombustivel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inpComb))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblQuil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inpQuil, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblPreco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inpPreco))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblProprietario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inpProprietario))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDataCad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inpDataCad)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarca)
                    .addComponent(inpMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModelo)
                    .addComponent(inpModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAno)
                    .addComponent(inpAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCor)
                    .addComponent(inpCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlaca)
                    .addComponent(inpPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChassi)
                    .addComponent(inpChassi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCombustivel)
                    .addComponent(inpComb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuil)
                    .addComponent(inpQuil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPreco)
                    .addComponent(inpPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProprietario)
                    .addComponent(inpProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataCad)
                    .addComponent(inpDataCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/projeto_avaliacao_1/view/images/salvar.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/projeto_avaliacao_1/view/images/novo.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/projeto_avaliacao_1/view/images/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/projeto_avaliacao_1/view/images/excluir.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/projeto_avaliacao_1/view/images/sair.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        tableVeiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Proprietário", "Modelo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableVeiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableVeiculosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableVeiculos);

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/projeto_avaliacao_1/view/images/pesquisar.png"))); // NOI18N
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(inpConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConsultar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(inpConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(201, 201, 201))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnNovo)
                    .addComponent(btnCancelar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        if(gravar_alterar == 1){
            gravar();
            gravar_alterar = 0;
        } else {
            if (gravar_alterar == 2){
                alterar();
                gravar_alterar = 0;
            } else {
                JOptionPane.showMessageDialog(null, "Erro no sistema!\n");
            }
        }
        
        limpaCampos();
        liberaBotoes(true, false, false, false, true);
        liberaCampos(false);
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        preencheTabela(inpConsultar.getText());
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void tableVeiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableVeiculosMouseClicked
        // TODO add your handling code here:
        preencheCampos(Integer.parseInt(String.valueOf(
                tableVeiculos.getValueAt(
                        tableVeiculos.getSelectedRow(), 0))));
        liberaBotoes(false, true, true, true, true);
        liberaCampos(true);
        gravar_alterar = 2;
    }//GEN-LAST:event_tableVeiculosMouseClicked

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        excluir();
        limpaCampos();
        limpaTabela();
        liberaCampos(false);
        liberaBotoes(true, false, false, false, true);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        liberaCampos(false);
        liberaBotoes(true, false, false, false, true);
        limpaCampos();
        limpaTabela();
    }//GEN-LAST:event_btnCancelarActionPerformed

  private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnNovoActionPerformed
    // TODO add your handling code here:
    liberaCampos(true);

    liberaBotoes(false, true, true, false, true);

    gravar_alterar = 1;

  }// GEN-LAST:event_btnNovoActionPerformed

  public void setPosition() {
    Dimension d = this.getDesktopPane()
        .getSize();

    this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
  }

  private void liberaBotoes(boolean novo, boolean salvar, boolean cancelar, boolean excluir, boolean sair) {
    btnNovo.setEnabled(novo);
    btnSalvar.setEnabled(salvar);
    btnCancelar.setEnabled(cancelar);
    btnExcluir.setEnabled(excluir);
    btnSair.setEnabled(sair);
  }

  // TODO: ajustar campo DATA
  private void liberaCampos(boolean libera) {
    inpAno.setEnabled(libera);
    inpChassi.setEnabled(libera);
    inpComb.setEnabled(libera);
    inpCor.setEnabled(libera);
    inpDataCad.setEnabled(false);
    inpMarca.setEnabled(libera);
    inpModelo.setEnabled(libera);
    inpPlaca.setEnabled(libera);
    inpPreco.setEnabled(libera);
    inpProprietario.setEnabled(libera);
    inpQuil.setEnabled(libera);
  }

  private void limpaCampos() {
    inpAno.setText("");
    inpChassi.setText("");
    inpComb.setText("");
    inpCor.setText("");
    inpDataCad.setText("");
    inpMarca.setText("");
    inpModelo.setText("");
    inpPlaca.setText("");
    inpPreco.setText("");
    inpProprietario.setText("");
    inpQuil.setText("");
  }
  
  private void limpaTabela() {
    modelo_jtl_consultar_veiculo.setNumRows(0);
  }
  
  private void preencheTabela(String modelo) {
      try {
          limpaTabela();
          
          dto.setModelo(modelo);
          
          rs = ctr.buscarVeiculo(dto, 1);
          
          while(rs.next()){
              modelo_jtl_consultar_veiculo.addRow(new Object[]{
                  rs.getString("id"),
                  rs.getString("proprietario"),
                  rs.getString("modelo")
              });
          }
      }catch(Exception e){
          System.out.println("Erro SQL:" + e.getMessage());
      } finally {
          ctr.CloseDbHelper();
      }
  }
  
  private void preencheCampos(int id) {
      try {
           dto.setId(id);
           
           rs = ctr.buscarVeiculo(dto, 2);
           
           if(rs.next()){
                limpaCampos();
               
                inpAno.setText(rs.getString("ano"));
                inpChassi.setText(rs.getString("chassi"));
                inpComb.setText(rs.getString("combustivel"));
                inpCor.setText(rs.getString("cor"));
                inpDataCad.setText(rs.getString("data_registro"));
                inpMarca.setText(rs.getString("marca"));
                inpModelo.setText(rs.getString("modelo"));
                inpPlaca.setText(rs.getString("placa"));
                inpPreco.setText(rs.getString("preco"));
                inpProprietario.setText(rs.getString("proprietario"));
                inpQuil.setText(rs.getString("quilometragem"));
           }
      }catch(Exception e){
          System.out.println("Erro SQL:"+e.getMessage()); 
      } finally {
          ctr.CloseDbHelper();
      }
  }

  private void setDto() {
    dto.setAno(Integer.parseInt(inpAno.getText()));
    dto.setChassi(inpChassi.getText());
    dto.setCombustivel(inpComb.getText());
    dto.setCor(inpCor.getText());
    // todo: criar created_at
    if(gravar_alterar == 1){
        dto.setData_cadastro(LocalDate.now());
    }
    dto.setMarca(inpMarca.getText());
    dto.setModelo(inpModelo.getText());
    dto.setPlaca(inpPlaca.getText());
    dto.setPreco(Float.parseFloat(inpPreco.getText()));
    dto.setProprietario(inpProprietario.getText());
    dto.setQuilometragem(Double.parseDouble(inpQuil.getText()));
  }

  private void gravar() {
    try {
        setDto();
        JOptionPane.showMessageDialog(null, ctr.inserirVeiculo(dto));
        
    } catch (Exception e) {
      System.out.println("Erro ao gravar:" + e.getMessage());
    }
  }
  
  private void alterar(){
      try {
          setDto();
          JOptionPane.showMessageDialog(null, ctr.alterarVeiculo(dto));
      } catch (Exception e) {
          System.err.println("Erro ao atualizar:" + e.getMessage());
      }
  }

    private void excluir() {
        if(JOptionPane.showConfirmDialog(null, "Deseja realmente excluir esse veículo?", "Aviso", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, ctr.excluirVeiculo(dto));
        }
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField inpAno;
    private javax.swing.JTextField inpChassi;
    private javax.swing.JTextField inpComb;
    private javax.swing.JTextField inpConsultar;
    private javax.swing.JTextField inpCor;
    private javax.swing.JTextField inpDataCad;
    private javax.swing.JTextField inpMarca;
    private javax.swing.JTextField inpModelo;
    private javax.swing.JTextField inpPlaca;
    private javax.swing.JTextField inpPreco;
    private javax.swing.JTextField inpProprietario;
    private javax.swing.JTextField inpQuil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblChassi;
    private javax.swing.JLabel lblCombustivel;
    private javax.swing.JLabel lblCor;
    private javax.swing.JLabel lblDataCad;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblProprietario;
    private javax.swing.JLabel lblQuil;
    private javax.swing.JTable tableVeiculos;
    // End of variables declaration//GEN-END:variables
}
